### ISSUE TITLE
iCal string vs. number

### ISSUE THREAD

**Issue by tijo82** [klein0r/ioBroker.trashschedule#79] opened 2021-08-09 18:39 UTC
### The problem

Ich bekomme folgenden Fehler seit letztem Update:

trashschedule.0 | 2021-08-09 20:30:07.229 | info | State value to set for "trashschedule.0.type.rest.nextWeekday" has to be type "string" but received type "number"

Ich verwende die aktuellen Versionen von iCal (1.11.2) und Trash Schedule (1.2.0)

### Version of ioBroker js-controller

3.3

### Version of Adapter

1.2.0

### Operating system running ioBroker

Docker on Synology

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment] 2021-08-10 15:19
Duplicate of #65

Siehe FAQ: https://github.com/klein0r/ioBroker.trashschedule/blob/master/faq_de.md

**Closed by klein0r** 2021-08-10 15:19 UTC
