### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Schimi1983** [klein0r/ioBroker.trashschedule#208] opened 2023-12-22 18:54 UTC
### The problem

Hi,

seit dem update auf 3.1.1 kommt die fehlermeldung und der Adapter bleibt Rot....

Mit 2.3 funktioniert alles einwandfrei....

### Version of nodejs

18.19

### Version of ioBroker js-controller

5.0.17

### Version of Adapter

3.1.1

### Operating system running ioBroker

Raspbian

### Checklist of files to include below

- [X] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

### Additional information & file uploads

<html>
<body>

host.smarthome | 2023-12-22 19:48:25.523 | info | Restart adapter system.adapter.trashschedule.0 because enabled
-- | -- | -- | --
host.smarthome | 2023-12-22 19:48:25.523 | error | instance system.adapter.trashschedule.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.smarthome | 2023-12-22 19:48:25.523 | error | Caught by controller[1]: at processTicksAndRejections (node:internal/process/task_queues:95:5)
host.smarthome | 2023-12-22 19:48:25.523 | error | Caught by controller[1]: at ObjectsInRedisClient._readDir (/opt/iobroker/node_modules/@iobroker/db-objects-redis/src/lib/objects/objectsInRedisClient.ts:1468:26)
host.smarthome | 2023-12-22 19:48:25.522 | error | Caught by controller[1]: at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/maybeCallback.ts:136:17)
host.smarthome | 2023-12-22 19:48:25.522 | error | Caught by controller[1]: Error: Not exists
host.smarthome | 2023-12-22 19:48:25.522 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
trashschedule.0 | 2023-12-22 19:48:24.867 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
trashschedule.0 | 2023-12-22 19:48:24.865 | info | terminating
trashschedule.0 | 2023-12-22 19:48:24.864 | info | cleaned everything up...
trashschedule.0 | 2023-12-22 19:48:24.825 | error | Not exists
trashschedule.0 | 2023-12-22 19:48:24.825 | error | Error: Not exists at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/maybeCallback.ts:136:17) at ObjectsInRedisClient._readDir (/opt/iobroker/node_modules/@iobroker/db-objects-redis/src/lib/objects/objectsInRedisClient.ts:1468:26) at processTicksAndRejections (node:internal/process/task_queues:95:5)
trashschedule.0 | 2023-12-22 19:48:24.658 | error | unhandled promise rejection: Not exists
trashschedule.0 | 2023-12-22 19:48:24.657 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
trashschedule.0 | 2023-12-22 19:48:24.572 | info | [ical] found configured ical event "Urlaub" without "display" flag. Activate the display flag on this entry if this is a relevant "trash event".
trashschedule.0 | 2023-12-22 19:48:24.569 | info | [ical] configurured ical preview is 31 days (until 08.01.2030) - increase this value to find more events in the future
trashschedule.0 | 2023-12-22 19:48:24.145 | info | starting. Version 3.1.1 in /opt/iobroker/node_modules/iobroker.trashschedule, node: v18.19.0, js-controller: 5.0.17
host.smarthome | 2023-12-22 19:48:21.407 | info | instance system.adapter.trashschedule.0 started with pid 45224
host.smarthome | 2023-12-22 19:48:20.921 | info | "system.adapter.trashschedule.0" enabled

</body>
</html>

**Comment by klein0r** [comment] 2023-12-22 18:58
Duplicate of #207 and fixed in 3.1.2

**Closed by klein0r** 2023-12-22 18:58 UTC
Labels: bug
