### ISSUE TITLE
Falscher Variablentyp

### ISSUE THREAD

**Issue by mguenther1** [klein0r/ioBroker.trashschedule#85] opened 2021-11-05 10:25 UTC
### The problem

Bekomme seit einiger Zeit folgende Logeinträge:

State value to set for "trashschedule.0.type.xxxxx.nextWeekday" has to be type "string" but received type "number" 

### Version of ioBroker js-controller

3.3.18

### Version of Adapter

1.2.0

### Operating system running ioBroker

Linux auf RP4 8GB

### Checklist of files to include below

- [ ] iobroker.current.log (Please share the logs in debug mode)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)

**Comment by klein0r** [comment] 2021-11-05 13:13
Liest eigentlich niemand die FAQ? Oder sucht nach geschlossenen Issues? 😄 

https://github.com/klein0r/ioBroker.trashschedule/blob/master/faq_de.md#state-value-to-set-for-trashschedule0typexxxnextweekday-has-to-be-type-string-but-received-type-number

**Comment by klein0r** [comment] 2021-11-05 13:14
duplicate of #83 #79 #65

**Closed by klein0r** 2021-11-05 13:14 UTC
